"""Data models for the Macroeconomic News Release Analyst Agent."""

from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class ImpactLevel(str, Enum):
    """Impact level for economic indicators."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Sentiment(str, Enum):
    """Sentiment classification."""

    BULLISH = "bullish"
    BEARISH = "bearish"
    NEUTRAL = "neutral"


class NewsItem(BaseModel):
    """A single news item from any data source."""

    id: str = Field(description="Unique identifier")
    title: str = Field(description="News headline")
    content: str = Field(description="Full content or summary")
    source: str = Field(description="Data source name")
    url: Optional[str] = Field(default=None, description="Link to original")
    published_at: datetime = Field(description="Publication timestamp")
    impact_level: ImpactLevel = Field(default=ImpactLevel.MEDIUM, description="Impact level")
    is_noise: bool = Field(default=False, description="Whether filtered as noise")
    is_manipulation: bool = Field(default=False, description="Whether flagged as manipulation")
    raw_sentiment_score: float = Field(default=0.0, description="Raw sentiment score (-1 to 1)")
    sentiment: Sentiment = Field(default=Sentiment.NEUTRAL, description="Classified sentiment")


class EconomicIndicator(BaseModel):
    """An economic indicator release."""

    id: str = Field(description="Unique identifier")
    name: str = Field(description="Indicator name (e.g., 'Non-Farm Payrolls')")
    country: str = Field(description="Country code (e.g., 'US')")
    release_time: datetime = Field(description="Scheduled release time")
    impact_level: ImpactLevel = Field(description="Expected market impact")
    previous_value: Optional[str] = Field(default=None, description="Previous release value")
    forecast_value: Optional[str] = Field(default=None, description="Consensus forecast")
    actual_value: Optional[str] = Field(default=None, description="Actual released value")


class SentimentBriefing(BaseModel):
    """A sentiment briefing generated by the agent."""

    id: str = Field(description="Unique identifier")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    briefing_type: str = Field(description="Type: 'daily' or 'high_impact'")
    title: str = Field(description="Briefing title")
    summary: str = Field(description="Executive summary")
    overall_sentiment: Sentiment = Field(description="Overall market sentiment")
    key_points: list[str] = Field(default_factory=list, description="Key bullet points")
    news_items: list[NewsItem] = Field(default_factory=list, description="Related news items")
    indicators: list[EconomicIndicator] = Field(
        default_factory=list, description="Related indicators"
    )
    content_hash: str = Field(default="", description="Hash to detect duplicates")
    sent: bool = Field(default=False, description="Whether notification was sent")
    sent_at: Optional[datetime] = Field(default=None, description="When notification was sent")


class UpcomingRelease(BaseModel):
    """Upcoming economic data release schedule entry."""

    indicator: EconomicIndicator
    notified: bool = Field(default=False, description="Whether pre-release notification sent")
